version: "1.0"

services:
kafka-ui:
  container_name: kafka-ui
  image: provectuslabs/kafka-ui:latest
  ports:
    - "8080:8080"
  depends_on:
    - zookeeper-kafka
    - kafka
  environment:
    KAFKA_CLUSTERS_0_NAME: local
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-kafka:2181
    KAFKA_CLUSTERS_0_JMXPORT: 9997
