#docker-compose.yml with
version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    ports:
      - "8098:8098"
    environment:
      #- KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:8098
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
volumes:
  kafka-data:
