#docker-compose.yml
version: "1"
services:
  producer-with-json:
    build:
      context: ./01-Sale-Order-Service/03-Producer-with-JSON
      dockerfile: Dockerfile
    image: producer-with-json
    container_name: producer-with-json
    ports:
      - 6501:6501
  producer-with-avro:
    build:
      context: ./01-Sale-Order-Service/04-Producer-with-avro
      dockerfile: Dockerfile
    image: producer-with-avro
    container_name: producer-with-avro
    ports:
      - 8001:8001
  

 
      
      
    
volumes:
#networks:
#default:
#name: my-network
#external: true
